// переменные меню
static int isJb = 1; 
static bool userInteraction = true;
static bool secondInteraction = false;

// функции 

float sliderX = 0.0f, sliderY = 0.0f;
int FlyingHeight = 10;
int Xhit = 5;

static bool noclip = false;
static bool Plock = false;

id<MTLTexture> VladimirTexture;

uint64_t GetTypeOffset;
uint64_t FindObjectsOffset;
uint64_t GetNameOffset;
uint64_t GetName2Offset;
uint64_t GetPlayerInfoOffset;
uint64_t FindObjectOffset;
uint64_t GetRigidbodyOffset;


uint64_t NoGrassOffset;
uint64_t ExtendedBuildOffset;
uint64_t SoulOffset;
uint64_t NoShakeOffset;
uint64_t ForceBuildOffset;
uint64_t MttOffset1;
uint64_t MttOffset2;
uint64_t MttOffset3;
uint64_t MttOffset4;
uint64_t MttOffset5;
uint64_t MttOffset6;
uint64_t UnderWaterOffset;
uint64_t NoFallDamageOffset1;
uint64_t NoFallDamageOffset2;
uint64_t NoFallDamageOffset3;
uint64_t FakeOwnerOffset1;
uint64_t FakeOwnerOffset2;
uint64_t FakeOwnerOffset3;
uint64_t FakeOwnerOffset4;
uint64_t NoSpreadOffset1;
uint64_t NoSpreadOffset2;
uint64_t NoRecoilOffset;
uint64_t PictureOffset;
uint64_t LockTimeOffset;
uint64_t NoTreeOffset;
uint64_t NameOffset;
uint64_t NoTextureOffset;
uint64_t BpOff1;
uint64_t BpOff2;
uint64_t BpOff3;
uint64_t BpOff4;
uint64_t BpOff5;
uint64_t BpOff6;
uint64_t BpOff7;
uint64_t BpOff8;
uint64_t BpOff9;
uint64_t BpOff10;
uint64_t BpOff11;
uint64_t BpOff12;
uint64_t BpOff13;
uint64_t BpOff14;
uint64_t BpOff15;
uint64_t BpOff16;
uint64_t BpOff17;
uint64_t BpOff18;
uint64_t BpOff19;
uint64_t BpOff20;
uint64_t BpOff21;
uint64_t BpOff22;
uint64_t BpOff23;
uint64_t BpOff24;
uint64_t BpOff25;
uint64_t BpOff26;
uint64_t BpOff27;
uint64_t BpOff28;
uint64_t BpOff29;
uint64_t BpOff30;
uint64_t BpOff31;
uint64_t BpOff32;
uint64_t BpOff33;
uint64_t BpOff34;
uint64_t BpOff35;
uint64_t BpOff36;
uint64_t BpOff37;
uint64_t BpOff38;
uint64_t BpOff39;
uint64_t BpOff40;
uint64_t BpOff41;
uint64_t BpOff42;
uint64_t BpOff43;
uint64_t BpOff44;
uint64_t BpOff45;
uint64_t BpOff46;
uint64_t BpOff47;
uint64_t BpOff48;
uint64_t BpOff49;
uint64_t BpOff50;
uint64_t BpOff51;
uint64_t BpOff52;
uint64_t BpOff53;
uint64_t BpOff54;
uint64_t BpOff55;
uint64_t BpOff56;
uint64_t BpOff57;
uint64_t BpOff58;
uint64_t BpOff59;
uint64_t BpOff60;
uint64_t BpOff61;
uint64_t BpOff62;
uint64_t BpOff63;
uint64_t BpOff64;
uint64_t BpOff65;
uint64_t BpOff66;
uint64_t BpOff67;
uint64_t BpOff68;
uint64_t BpOff69;
uint64_t BpOff70;
uint64_t BpOff71;
uint64_t BpOff72;
uint64_t BpOff73;
uint64_t BpOff74;
uint64_t BpOff75;
uint64_t BpOff76;
uint64_t BpOff77;
uint64_t BpOff78;
uint64_t BpOff79;
uint64_t BpOff80;
uint64_t BpOff81;
uint64_t BpOff82;
uint64_t BpOff83;
uint64_t BpOff84;
uint64_t BpOff85;
uint64_t BpOff86;
uint64_t BpOff87;
uint64_t BpOff88;
uint64_t BpOff89;
uint64_t BpOff90;
uint64_t BpOff91;
uint64_t BpOff92;
uint64_t BpOff93;
uint64_t BpOff94;
uint64_t InstantExpOffset;
uint64_t AdmEspOffset;
uint64_t NoEnemyAnimOffset1;
uint64_t NoEnemyAnimOffset2;
uint64_t RpgOffOffset;
uint64_t DrinkWaterOffset;
uint64_t SetVelocityOffset;
uint64_t GetVelocityOffset;
uint64_t SetIsKinematicOffset;
uint64_t SetGroundedOffset;
uint64_t SetDetectCollisionsOffset;
uint64_t GetPositionOffset;
uint64_t GetForwardOffset;
uint64_t GetTransformOffset;
uint64_t CameraOffset;
uint64_t W2WPOffset;
uint64_t IsAliveObjectOffset;
uint64_t SetPositionOffset;


// функции меню

static bool notexture = false;    
static bool instantexp= false;    
static bool instantrpg= false;    
static bool name = false;    
static bool nograss = false;                    
static bool locktime = false;        
static bool picture = false;      
static bool norecoil = false;     
static bool nospread = false;     
static bool fakeowner = false;     
static bool nofalldamage = false;     
static bool underwater = false;     
static bool mtt = false;     
static bool forcebuild = false;     
static bool noshake = false;     
static bool soul = false;     
static bool gm = false;     
static bool exbuild = false;
static bool bypass = false;     
static bool notree = false;     
static bool admesp = false; 
static bool noenemyanim = false;
static bool traceroff = false;
static bool rpgoff = false;
static bool drinkwater = false;

static bool notexture_active = false;
static bool instantexp_active = false;
static bool instantrpg_active = false;
static bool name_active = false;
static bool nograss_active = false;
static bool locktime_active = false;
static bool picture_active = false;
static bool norecoil_active = false;
static bool nospread_active = false;
static bool fakeowner_active = false;
static bool nofalldamage_active = false;
static bool underwater_active = false;
static bool mtt_active = false;
static bool forcebuild_active = false;
static bool noshake_active = false;
static bool soul_active = false;
static bool gmm_active = false;
static bool exbuild_active = false;
static bool bypass_active = false;
static bool notree_active = false;
static bool admesp_active = false;
static bool noenemyanim_active = false;
static bool traceroff_active = false;
static bool rpgoff_active = false;
static bool drinkwater_active = false;


static bool magic06;
static bool magic12;
static bool knife06;
static bool knife12;
static bool knife120;
static bool magic120;
static bool lootroom;
static bool skybuild;
static bool firerate;
static bool x8scope;
static bool magicbullet;
static bool magicknife;
static bool underground;
static bool drivermale;
static bool drivergirl;
static bool cameradown;
static bool highfov;
static bool antideath;
static bool highjump;
static bool x10scope;
static bool whitebody;
static bool blackbody;
static bool waterbuild;
static bool timechange;
static bool blacksky;
static bool mapfog;
static bool deletemap;
static bool fastbike;


